GET http://localhost:8080/professional


### LOCAL
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/6442ea2f82968e0ada1da14d
###
GET http://localhost:8080/contacts/6442ea3d82968e0ada1da14e
###
GET http://localhost:8080/contacts/6442ea4882968e0ada1da14f

### RENDER

GET https://cse341-w02.onrender.com/contacts
###
GET https://cse341-w02.onrender.com/contacts/6442ea2f82968e0ada1da14d
###
GET https://cse341-w02.onrender.com/contacts/6442ea3d82968e0ada1da14e
###
GET https://cse341-w02.onrender.com/contacts/6442ea4882968e0ada1da14f

### CREATE CONTACT
POST https://cse341-w02.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Lila",
        "lastName": "Ourth",
        "email": "lila123@gmail.com",
        "favColor": "purple",
        "birthday": "03/19/99"
}

### PUT CONTACT
PUT https://cse341-w02.onrender.com/contacts6442ea2f82968e0ada1da14d HTTP/1.1
content-type: application/json

{
    "firstName": "Jill",
        "lastName": "Ourth",
        "email": "jilliour@yahoo.com",
        "favColor": "turquoise",
        "birthday": "07/08/82"
}

### DELETE CONTACT
DELETE http://localhost:8080/contacts/ HTTP/1.1